[package]
name = "ruby_build_test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell="1.8.0"
rutie="0.8.2"
dlopen = "0.1"
dlopen_derive = "0.1.4"
tempfile = "3.2.0"
